### ISSUE TITLE
Glossario

### ISSUE THREAD

**Issue by AlessandroTigani** [Project-SWEnergy/doc-latex#100]
- [x] Descritto in "Norme di progetto".
- [x] Redazione.
- [x] Verifica.
- [x] Approvazione.
- [x] Automazione

### Automazione

Programma che cerca la presenza delle parole che compongono il glossario all'interno della documentazione e ne inserisce un riferimento

**Comment by bandomatteo** [comment]
- [ ] Da aggiungere "Matteo Bando" nei redattori

**Comment by danesinoo** [comment]
Io toglierei i redattori del Glossario: dal momento che abbiamo scritto che siamo tenuti a redigerlo tutti, non inseriamo i redattori. Piuttosto ci sarà un registro delle modifiche in cui si vede chi ha scritto che cosa

**Comment by danesinoo** [comment]
Direi che il documento deve essere verificato con cadenza settimanale e approvato con cadenza mensile. Nessuno dei due finali. Sia i redattori che i verificatori e gli approvatori saranno visibili nel registro delle modifiche. Per la natura del documento, non mi sembra che risulti necessario aggiungere questi nomi nella copertina
