### ISSUE TITLE
Norme di progetto

### ISSUE THREAD

**Issue by AlessandroTigani** [Project-SWEnergy/doc-latex#104]
- [x] Aggiornamento gestione Issues con Projects.
- [x] Gestione branch.
- [x] Aggiornamento verbali interni con ruoli assegnati.
- [x] Aggiornamento templates creazione documenti.
- [x] #137 
- [x] #156

**Comment by danesinoo** [comment]
# Documentazione
- non serve spiegare la struttura di ciascun documento perché
  - la struttura viene definita ed usata una volta sola
  - risulta più semplice per un lettore trovare la descrizione della struttura all'interno del documento medesimo
- struttura dei verbali interni
- struttura dei verbali esterni
- struttura dei diari di bordo
- Glossario: come individuaimo le parole che inseriamo nel glossario?
# Ruoli
- compiti che sono svolti da ciascun ruolo
- sopostare la porzione di compiti svolti dal responsabile dal Piano di progetto a alle Norme di progetto
