### ISSUE TITLE
Analisi dei requisiti

### ISSUE THREAD

**Issue by danesinoo** [Project-SWEnergy/doc-latex#95]
- [x] schemi
- [x] bozza
- [x] stesura
- [x] verifica
- [x] correzione dopo il confronto con l'azienda

## Bozza
La bozza deve essere un documento definitivo, per le informazioni che abbiamo.  
Deve essere ben scritta. Non può essere il documento definitivo perché implementando i requisiti ci renderemo conto che qualcuno lo abbiamo saltato. Dobbiamo cercare di prevedere tutti gli scenari, comunque.

**Comment by Guala02** [comment]
QUINDI, Da aggiungere:
3.3) Modifica pietanza (rimuovendo ingredienti, o selezionando la quantità(per persone che seguono una dieta ecc...) o rimuovendone alcuni (per intolleranze, o per gusto personale))

16)Creazione lista ingredienti.
17)Modifica lista ingredienti.   (Entrambe effettuate dall'utente ristorante/business)
18) L'utente business può aggiungere un ristorante e relativi piatti. Esso avrà vari sotto use case.
Per inserire nome del ristorante, tipologia della cucina, fascia del prezzo, ingredienti principali ecc....

UC-5.1)L'utente ha la possibilità di lasciare una mancia.
UC-19) Monitoraggio online:
L'utente ha la possibilità di monitorare online lo stato del proprio ordine con relativa notifica push di quando esso è pronto ed è in stato di consegna.

UC-20) Sistema di notifiche:
L'utente autenticato, se accetta vari termini e acconsente al trattamento dati e ricezione pubblicità, può riceveer promozioni, sconti, lista di ristoranti nuovi ecc... 

UC-21) Sistema di filtraggio:
L'utente che si trova nella home page, può filtrare la lista dei ristoranti disponibili, attraverso GPS e quindi ristoranti più vicini (altro UC, da gestire), per prezzo, per orario, per sconti, popolarità, cucina ecc...
UC-21) Tracciamento GPS:
L'utente, qualora lo desidera può accettare il tracciamento, per avere un'esperienza migliore, ad esempio per il filtraggio dei ristoranti (vedi UC-21)

UC-22) L'utente ristorante/business riceve una notifica quando il suo ristorante riceve un feedback.
Inoltre ha la possibilità di segnalarlo, se contiene contenuto falso, disperegiativo o offensivo, il quale notificherà il sistema. (REQUISITO SULLA SICUREZZA?)

**Comment by Guala02** [comment]
NICE TO HAVE:
1) Ordinare da asporto.
2) Gestire eventuali consegne.
3) Condivisione sui social media.
4) Possibilità di richiedere un Uber senza uscire dalla webapp.

**Comment by Guala02** [comment]
Nella modifica di una lista di ingredienti e creazione di una lista di ingredienti si potrà andare ancora più in dettaglio per aggiungere un ingrediente, eliminarlo o modificarlo.

Non bisogna aggiungere la conferma di prenotazione, in modo tale da poi avere e gestire il monitoraggio di un ordine.

**Comment by Guala02** [comment]
Nel UC-16, voglio fare in modo che si assegni un ingrediente a una o più pietanze in modo tale che l'utente visualizzi solamente gli ingredienti associati ad una pietanza o quelli consigliati da aggiungere a quella pietanza e non tutta la lista completa (escludento anche gli ingredienti non disponibili).
Inoltre la quantità: se il cliente vuole aggiungere un ingredeinte e anche la quantità, se per caso nella lista la quantità non è sufficiente il sitema avverte la mancata quantità al utente ristoratore che andrà a comprarla?

**Comment by danesinoo** [comment]
## UC-(3, 3.1, 5.1, 8, 14)

Hai ragione, possono essere spiegati meglio. In particolare, aggiungere la possibilità di lasciare una mancia per UC-5.1.

## UC-10

Specificare i parametri di ricerca di un ristorante: posizione, prezzo, orario, popolarità e cucina (sconti ricade dentro prezzo?)

### UC-10.1

Filtro della posizione automatico

## UC-12 - Specificare il modo in cui il link è condiviso

Io lascerei vaquo quello che può fare l'utente dopo che ha copiato il link, perché rischia di diventare progettazione: 
- a seconda del dispositivo adoperato i metodi di condivisione variano.
- l'utente è più flessibile: avendo solo il link può adottare la tecnologia che preferisce per condividerlo. Fondamentalmente, può usare anche tecnologie che ancora non esistono.

## UC-14

In particolare, l'UC-14 è un'estensione dell'UC-13. Possiamo specificarlo. Avevo l'impressione che ci fossero anche altre circostanze in cui il sistema non permette all'utente ristoratore di comportarsi come un utente base. Purtroppo non le ho scritte da nessuna parte e non mi vengono in mente. Per risolvere l'ambiguità, aggiungerei una sezione "descrizione" a questo caso d'uso.

## UC-15

Nell'UC-15 non è presente la frase riportata. L'UC-7 è simile e c'è la frase riportata con l'aggiunta "dopo aver completato un ordine". Perché come hai ben detto si può inserire un feedback solo dopo il completamento dell'ordine. 
**NB** L'UC-15 specifica che l'utente base può inserire un feedback solo dopo che l'ordine è stato completato.
**NB** L'UC-15 invia una notifica push, dopo che il feedback è stato salvato nel database.

## Nice-to-have

- Non gestirei le consegne. Se dovessi fare un'applicazione di questo tipo, piuttosto costruirei le API per appoggiarsi ad un'APP di gestione delle consegne. In entrambe i casi, deve essere disponibile il pagamento in app. 

- Quindi si aggiunge anche lo use case di pagamento in app.

Non ho commenti per gli altri nice-to-have

**Comment by danesinoo** [comment]
> Inoltre la quantità: se il cliente vuole aggiungere un ingredeinte e anche la quantità, se per caso nella lista la quantità non è sufficiente il sitema avverte la mancata quantità al utente ristoratore che andrà a comprarla?

Si deve aggiungere uno use case in cui il ristoratore indica le quantità degli ingredienti che ha. Una sorta di registro del magazzino.
